Build root for codeql

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -13,70 +13,119 @@ name: "CodeQL"
 
 on:
   push:
-    branches: [ "codecov" ]
+    branches: [ "codeql" ]
   pull_request:
     # The branches below must be a subset of the branches above
-    branches: [ "codecov" ]
+    branches: [ "codeql" ]
   schedule:
     - cron: '25 6 * * 3'
 
 jobs:
-  analyze:
-    name: Analyze
-    # Runner size impacts CodeQL analysis time. To learn more, please see:
-    #   - https://gh.io/recommended-hardware-resources-for-running-codeql
-    #   - https://gh.io/supported-runners-and-hardware-resources
-    #   - https://gh.io/using-larger-runners
-    # Consider using larger runners for possible analysis time improvements.
-    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
-    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
-    permissions:
-      actions: read
-      contents: read
-      security-events: write
+  
+  # analyze:
+  #   name: Analyze
+  #   # Runner size impacts CodeQL analysis time. To learn more, please see:
+  #   #   - https://gh.io/recommended-hardware-resources-for-running-codeql
+  #   #   - https://gh.io/supported-runners-and-hardware-resources
+  #   #   - https://gh.io/using-larger-runners
+  #   # Consider using larger runners for possible analysis time improvements.
+  #   runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
+  #   # timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
+  #   # permissions:
+  #   #   actions: read
+  #   #   contents: read
+  #   #   security-events: write
 
-    strategy:
-      fail-fast: false
-      matrix:
-        language: [ 'cpp', 'csharp', 'go', 'javascript', 'python' ]
-        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby', 'swift' ]
-        # Use only 'java' to analyze code written in Java, Kotlin or both
-        # Use only 'javascript' to analyze code written in JavaScript, TypeScript or both
-        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       language: [ 'cpp', 'csharp', 'go', 'javascript', 'python' ]
+  #       # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby', 'swift' ]
+  #       # Use only 'java' to analyze code written in Java, Kotlin or both
+  #       # Use only 'javascript' to analyze code written in JavaScript, TypeScript or both
+  #       # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support
 
-    steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+    
+  #   # Initializes the CodeQL tools for scanning.
+  #   # - name: Initialize CodeQL
+  #   #   uses: github/codeql-action/init@v2
+  #   #   with:
+  #   #     languages: ${{ matrix.language }}
+  
+  
+  Analyze:
+    
+      # if: github.repository_owner == 'root-project' || github.event_name == 'pull_request'
+  
+      permissions:
+        contents: read
+        actions: read
+        security-events: write
+  
+      runs-on: 
+        - self-hosted
+        - linux
+        - x64
+  
+      name: Build and test to determine coverage
+  
+      container:
+        image: registry.cern.ch/root-ci/fedora38:buildready
+        options: '--security-opt label=disable --rm'
+        env:
+          OS_APPLICATION_CREDENTIAL_ID: '7f5b64a265244623a3a933308569bdba'
+          PYTHONUNBUFFERED: true
+  
+      steps:
+  
+        - name: Checkout
+          uses: actions/checkout@v3
+  
+        - name: Dump GitHub context
+          env:
+            GITHUB_CONTEXT: ${{ toJSON(github) }}
+          run: echo "$GITHUB_CONTEXT"
+  
+        - name: Print debug info
+          run:  'printf "%s@%s\\n" "$(whoami)" "$(hostname)";
+                 ls -la
+                '
+        
+  
+        - name: Apply option override from matrix for this job
+          env:
+            OVERRIDE: "coverage=On"
+            FILE: .github/workflows/root-ci-config/buildconfig/fedora38.txt
+          shell: bash
+          run: |
+            set -x
+  
+            echo '' >> "$FILE"
+            echo $OVERRIDE >> "$FILE"
+            cat "$FILE" || true
+        
+        # Initializes the CodeQL tools for scanning.
+        - name: Initialize CodeQL
+          uses: github/codeql-action/init@v2
+          with:
+            languages: 'cpp'
+  
+        # - name: Pull Request Build
+        - name: Push Request Build
+          # if: github.event_name == 'pull_request'
+          # env:
+            # GITHUB_PR_ORIGIN: ${{ github.event.pull_request.head.repo.clone_url }}
+          run: ".github/workflows/root-ci-config/build_root.py
+                      --buildtype      Debug
+                      --platform       fedora38
+                      --incremental    false
+                      --base_ref       ${{ github.base_ref }}
+                      --head_ref       refs/pull/${{ github.event.pull_request.number }}/head:${{ github.event.pull_request.head.ref }}
+                      --repository     ${{ github.server_url }}/${{ github.repository }}
+                "
 
-    # Initializes the CodeQL tools for scanning.
-    - name: Initialize CodeQL
-      uses: github/codeql-action/init@v2
-      with:
-        languages: ${{ matrix.language }}
-        # If you wish to specify custom queries, you can do so here or in a config file.
-        # By default, queries listed here will override any specified in a config file.
-        # Prefix the list here with "+" to use these queries and those in the config file.
 
-        # For more details on CodeQL's query packs, refer to: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
-        # queries: security-extended,security-and-quality
-
-
-    # Autobuild attempts to build any compiled languages (C/C++, C#, Go, Java, or Swift).
-    # If this step fails, then you should remove it and run the build manually (see below)
-    - name: Autobuild
-      uses: github/codeql-action/autobuild@v2
-
-    # ℹ️ Command-line programs to run using the OS shell.
-    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
-
-    #   If the Autobuild fails above, remove it and uncomment the following three lines.
-    #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.
-
-    # - run: |
-    #     echo "Run, Build Application using script"
-    #     ./location_of_script_within_repo/buildscript.sh
-
-    - name: Perform CodeQL Analysis
-      uses: github/codeql-action/analyze@v2
-      with:
-        category: "/language:${{matrix.language}}"
+        - name: Perform CodeQL Analysis
+          uses: github/codeql-action/analyze@v2
+          with:
+            category: "/language:cpp"
